version: '3.8'

services: 
  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock_api
    ports:
      - "8081:80"
  
  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: emailing-service
    ports:
      - "8082:80"
  
  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: supply-service
    ports:
      - "8083:80"

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees-service
    ports:
      - "8084:80"

  merchandise-service:
    build: ..
    hostname: merchandise-service
    ports:
      - "8085:80"

  merchandise-db:
    image: postgres:latest
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchDBPassword
      POSTGRES_DB: merch-db
    command: "-c log_statement=all"
  